---
- name: Download Application from Nexus Repo
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('jenkins') }}"
  become: yes
  tasks:
    - name: Download war file from Nexus 
      copy:
        src: "{{ ARTIFACT_URL }}"
        dest: "/opt/tomcat/webapps/ROOT.war"
      notify:
        - Restart tomcat
      
  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
